// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    // Test name: test1
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1097x1034 | 
    driver.manage().window().setSize(new Dimension(1097, 1034));
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
    // 4 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
    // 5 | click | css=.btn-success | 
    driver.findElement(By.cssSelector(".btn-success")).click();
    // 6 | click | id=ageInput | 
    driver.findElement(By.id("ageInput")).click();
    // 7 | type | id=ageInput | 18
    driver.findElement(By.id("ageInput")).sendKeys("18");
    // 8 | click | css=.alert | 
    driver.findElement(By.cssSelector(".alert")).click();
    // 9 | mouseDownAt | css=.btn-success | 44.65625,26.09375
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 10 | mouseMoveAt | css=.btn-success | 44.65625,26.09375
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 11 | mouseUpAt | css=.btn-success | 44.65625,26.09375
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 12 | click | css=.btn-success | 
    driver.findElement(By.cssSelector(".btn-success")).click();
    // 13 | click | id=ageInput | 
    driver.findElement(By.id("ageInput")).click();
    // 14 | type | id=ageInput | 18.001
    driver.findElement(By.id("ageInput")).sendKeys("18.001");
    // 15 | click | css=.ng-submitted | 
    driver.findElement(By.cssSelector(".ng-submitted")).click();
    // 16 | click | css=.btn-success | 
    driver.findElement(By.cssSelector(".btn-success")).click();
    // 17 | mouseOver | css=.btn-success | 
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 18 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
    // 19 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
    // 20 | click | css=.btn-success | 
    driver.findElement(By.cssSelector(".btn-success")).click();
    // 21 | assertValue | css=tr:nth-child(4) > .ng-binding | 0
    {
      String value = driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getAttribute("value");
      assertThat(value, is("0"));
    }
  }
}
